<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="44959" started-at="2018-05-07T15:17:25Z" finished-at="2018-05-07T15:18:10Z">
    <groups>
      <group name="regression">
        <method signature="Scenario_Login.testValidLogin(java.util.Map)[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="testValidLogin" class="Scenario_Component.Scenario_Login"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="Scenario_Login.testInvalidLogin(java.util.Map)[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="testInvalidLogin" class="Scenario_Component.Scenario_Login"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="44959" started-at="2018-05-07T15:17:25Z" finished-at="2018-05-07T15:18:10Z">
      <class name="Scenario_Component.Scenario_Login">
        <test-method status="PASS" signature="LaunchApp()[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="LaunchApp" is-config="true" duration-ms="16245" started-at="2018-05-07T08:17:28Z" finished-at="2018-05-07T08:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApp -->
        <test-method status="FAIL" signature="testInvalidLogin(java.util.Map)[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="testInvalidLogin" duration-ms="4374" started-at="2018-05-07T08:17:44Z" data-provider="dp_InvalidLogin" finished-at="2018-05-07T08:17:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Execute_Flag=Y, Uname=gfhg, TC_ID=GB_01, Script_name=InvalidLogin, Exp_Result=Sorry we were unable to complete this step , Pwd=dghfasf, Order_Set=1.0}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at Scenario_Component.Scenario_Login.testInvalidLogin(Scenario_Login.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="CloseApp()[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="CloseApp" is-config="true" duration-ms="1523" started-at="2018-05-07T08:17:49Z" finished-at="2018-05-07T08:17:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApp -->
        <test-method status="PASS" signature="LaunchApp()[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="LaunchApp" is-config="true" duration-ms="12565" started-at="2018-05-07T08:17:50Z" finished-at="2018-05-07T08:18:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApp -->
        <test-method status="PASS" signature="testValidLogin(java.util.Map)[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="testValidLogin" duration-ms="6562" started-at="2018-05-07T08:18:03Z" data-provider="dp_ValidLogin" finished-at="2018-05-07T08:18:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Execute_Flag=Y, Uname=qtpworld2008@gmail.com, TC_ID=GB_07, Script_name=ValidLogin, Exp_Result=qtpworld2008, Pwd=learn123, Order_Set=1.0}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method status="PASS" signature="CloseApp()[pri:0, instance:Scenario_Component.Scenario_Login@c0a365]" name="CloseApp" is-config="true" duration-ms="1154" started-at="2018-05-07T08:18:09Z" finished-at="2018-05-07T08:18:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApp -->
      </class> <!-- Scenario_Component.Scenario_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
